// internal/httpmw/recover.go

package httpmw

import (
	"net/http"
	"runtime/debug"

	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"

	"github.com/linnemanlabs/go-core/log"
	"github.com/linnemanlabs/go-core/xerrors"
)

// Recover is a middleware that recovers from panics in HTTP handlers, logs the panic with stack trace, and returns a 500 response.
// onPanic is an optional callback that is called when a panic occurs, e.g. to trigger alerts or increment prometheus counters, etc.
func Recover(base log.Logger, onPanic func()) func(next http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			defer func() {
				if rec := recover(); rec != nil {
					if onPanic != nil {
						onPanic()
					}
					ctx := r.Context()

					// Preserve underlying panic error type when possible.
					var recErr error
					if err, ok := rec.(error); ok {
						recErr = xerrors.Wrap(err, "httpserver panic")
					} else {
						recErr = xerrors.Newf("httpserver panic: %v", rec)
					}

					// Enrich base logger
					// we intentionally dont log user-supplied data here like query params, user-agent or other headers to avoid potential PII/log injection
					// all fields are either generated by us or come from the runtime which we control and have sanitized
					L := base.With(
						"panic", rec,
						"http_method", r.Method,
						"http_path", r.URL.Path,
						// "http_query", r.URL.Query(),
						"remote_addr", r.RemoteAddr,
						// "user_agent", r.UserAgent(),
					)

					// Full goroutine stack at time of panic.
					panicStack := debug.Stack()

					// Record into OTEL span.
					if span := trace.SpanFromContext(ctx); span != nil && span.IsRecording() {
						span.RecordError(recErr)
						span.SetStatus(codes.Error, "panic")
					}

					L.Error(ctx, recErr, "httpserver panic recovered",
						"panic_stack", string(panicStack),
					)

					http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
				}
			}()

			next.ServeHTTP(w, r)
		})
	}
}
